steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/vector-api:$COMMIT_SHA", "./backend"]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/vector-api:$COMMIT_SHA"]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: ["run", "deploy", "${_SERVICE}", "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/vector-api:$COMMIT_SHA", "--region=${_REGION}", "--platform=managed", "--allow-unauthenticated", "--port=8080", "--set-env-vars=DEBUG=false,CORS_ORIGINS=${_CORS_ORIGINS},FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}"]
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/vector-api:$COMMIT_SHA"
substitutions:
  _REGION: asia-south1
  _REPOSITORY: vector-prod
  _SERVICE: vector-api
  _CORS_ORIGINS: https://YOUR_FIREBASE_DOMAIN.web.app
  _FIREBASE_STORAGE_BUCKET: YOUR_GCP_PROJECT_ID.appspot.com
